
on: [issues]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Tag issues
    steps:
    - name: Issue tagging
      id: issue-autotagger
      uses: christopheranderson/issue-autotagger@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
